export const SPECIALTY_OPTIONS = [
  'Actor',
  'Actress',
  'Voice Actor',
  'Dancer',
  'Stunt Performer',
  'Presenter',
  'Screenwriter',
  'Script Editor',
  'Playwright',
  'Story Editor',
  'Director',
  'Assistant Director',
  'Stage Director',
  'Producer',
  'Executive Producer',
  'Line Producer',
  'Production Manager',
  'Casting Director',
  'Talent Coordinator',
  'Cinematographer',
  'Camera Operator',
  'Gaffer',
  'Sound Designer',
  'Composer',
  'Sound Mixer',
  'Production Designer',
  'Art Director',
  'Costume Designer',
  'Makeup Artist',
  'Editor',
  'Colorist',
  'VFX Artist',
  'Motion Designer',
  'Coach',
  'Agent',
  'Manager',
  'Distributor',
] as const;

export const FEATURED_SPECIALTIES = SPECIALTY_OPTIONS.slice(0, 8);
